### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thomasegense** [statsbiblioteket/graph_presenter#27]
Since GraphicsMagic has the kerning bug and VIPS can handle the PNG generation also, I would prefer GM was completely removed from the documentation and script. Also graphics magic requires insane amount of memory (and special swap option to even enable it), so it is not an option for most hardware anyway. And then drop the option VIPS_ONLY=true.

(Later when LIPVIPS 8.9 is released, remove the section about how to build it.. I thought was 
released already, but it was not sorry. The patch seems to be in the comming 8.9 release:
https://github.com/libvips/libvips/blob/master/ChangeLog
Add a LIPVIPS version check, must be 8.9 of higher : vips -v

**Comment by tokee** [comment]
Since older `vips` (the default under Ubuntu 18.04 for example) has a limit of 10MB for SVGs, removing `GraphicsMagic` would in effect _require_ users to compile `vips`. I do not see that as a realistic requirement.

A `vips` version-check and automatic enabling of `vips` and disabling of PNG in case of v8.9+ is fine.
